stages:
  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/dataset.csv
    outs:
      - models/model.pkl:
          cache: true
    metrics:
      - models/metrics.json:
          cache: false
